version: '3'
services:
  nodejs-api:
    build:
      context: .
    ports:
      - "6000:6000"
    container_name: api-travel
    restart: always
#    environment:
#      HTTPS_PROXY: http://192.168.36.35:3128